### ISSUE TITLE
[1.1] Can't spawn in a village

### ISSUE THREAD

**Issue by Traktool** [lemon-slice-studio/spawnvillage#1]
I've installed your mod cause I want a mod like this, but it doesn't spawn me in village
If I type the locate command, villages are about ~1000 ~1800 blocks far from the original spawn point
I've tried different parameters in the config, maximise all values etc, but nothing work

**Comment by Traktool** [comment]
I've just tried to set world generation to "Default" and it work, also with Biomes'O'Plenty generation
But not with TerraForged generationn don't know why

**Comment by jihuayu** [comment]
I search struct only 1000m, I will add a new config(struct-search-range).  
Thanks.

**Comment by jihuayu** [comment]
Please check have you set spawn-biome.
Struct is useless if spawn-biome is defined.

**Comment by Traktool** [comment]
Oh okay, and TerraForged generate village +1000 block away
No, I havent set spawn-biome

**Comment by Traktool** [comment]
Ok, with TerraForged generation I've a village at x:80 z:336 and it wont spawn me in, so I think TerraForged override the original spawn, so your mod can't override it again

**Comment by jihuayu** [comment]
It looks no problem in my world.
I am very sorry.
I will publish a new version, you can have a try.

**Comment by Traktool** [comment]
With the new version it works ! Just have to extend the searching radius
Tank you :D

**Comment by jihuayu** [comment]
ok.
